running with 1 processes on 1 nodes
Traceback (most recent call last):
  File "/home/bhchen/Software/miniconda3/lib/python3.9/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'Potential disk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhchen/Pipeline/Python/Simulation/Agama_IC/ic.py", line 101, in <module>
    iniPotenComps += [dict(ini.items("Potential "+comp.lower()))]
  File "/home/bhchen/Software/miniconda3/lib/python3.9/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Potential disk'
